// --- MODIFIERS LIST ---
const modifiers = [
    "Без брони",
    "Без прыжков",
    "Только вид от 3-го лица (F5)",
    "Без использования сундуков",
    "Нельзя получать урон от падения",
    "Пацифист (никого не убивать)",
    "Без использования ведра воды",
    "FOV: 30 (Максимальное приближение)",
    "FOV: Quake Pro",
    "Без бега",
    "Только кожаная броня",
    "Пол — это лава",
    "Режим крота (не выходи на поверхность)",
    "Ночной житель (выходи только ночью)",
    "Без использования щита",
    "Вегетарианец",
    "Карнивор",
    "Без крафта инструментов",
    "Слепота (Яркость: Mood)",
    "Без звука",
    "Инверсия мыши",
    "Только 5 слотов хотбара",
    "Без использования верстака",
    "Нельзя использовать кровать",
    "Предмет во второй руке всегда",
    "Нельзя плавать",
    "Только золотые инструменты",
    "Нельзя использовать факелы",
    "Cinematic Camera (F8)",
    "Без регенерации",
    "Нельзя ломать землю/дерн",
    "Нельзя ломать дерево",
    "Только деревянные инструменты",
    "Инвентарь: 1 ряд",
    "Нельзя открывать инвентарь",
    "Чувствительность мыши: Max",
    "Чувствительность мыши: Min",
    "Без интерфейса (F1)",
    "Монохром",
    "Нельзя использовать печь"
];

// --- EFFECTS LIST ---
const effects = [
    { id: "regeneration", name: "Регенерации" },
    { id: "swiftness", name: "Скорости" },
    { id: "fire_resistance", name: "Огнестойкости" },
    { id: "healing", name: "Лечения" },
    { id: "night_vision", name: "Ночного зрения" },
    { id: "strength", name: "Силы" },
    { id: "leaping", name: "Прыгучести" },
    { id: "invisibility", name: "Невидимости" },
    { id: "poison", name: "Отравления" },
    { id: "weakness", name: "Слабости" },
    { id: "slowness", name: "Замедления" },
    { id: "harming", name: "Урона" },
    { id: "water_breathing", name: "Подводного дыхания" },
    { id: "slow_falling", name: "Плавного падения" }
];

// --- COLORS ---
const colors = [
    { id: "white", root: "Бел", endM: "ый", endF: "ая", endN: "ое" },
    { id: "orange", root: "Оранжев", endM: "ый", endF: "ая", endN: "ое" },
    { id: "magenta", root: "Сиренев", endM: "ый", endF: "ая", endN: "ое" },
    { id: "light_blue", root: "Голуб", endM: "ой", endF: "ая", endN: "ое" },
    { id: "yellow", root: "Желт", endM: "ый", endF: "ая", endN: "ое" },
    { id: "lime", root: "Лаймов", endM: "ый", endF: "ая", endN: "ое" },
    { id: "pink", root: "Розов", endM: "ый", endF: "ая", endN: "ое" },
    { id: "gray", root: "Сер", endM: "ый", endF: "ая", endN: "ое" },
    { id: "light_gray", root: "Светло-сер", endM: "ый", endF: "ая", endN: "ое" },
    { id: "cyan", root: "Бирюзов", endM: "ый", endF: "ая", endN: "ое" },
    { id: "purple", root: "Фиолетов", endM: "ый", endF: "ая", endN: "ое" },
    { id: "blue", root: "Син", endM: "ий", endF: "яя", endN: "ее" },
    { id: "brown", root: "Коричнев", endM: "ый", endF: "ая", endN: "ое" },
    { id: "green", root: "Зелен", endM: "ый", endF: "ая", endN: "ое" },
    { id: "red", root: "Красн", endM: "ый", endF: "ая", endN: "ое" },
    { id: "black", root: "Черн", endM: "ый", endF: "ая", endN: "ое" }
];

// --- WOODS ---
const woods = [
    { id: "oak", name: "Дуб", root: "Дубов" },
    { id: "spruce", name: "Ель", root: "Елов" },
    { id: "birch", name: "Береза", root: "Березов" },
    { id: "jungle", name: "Тропич", root: "Тропическ" },
    { id: "acacia", name: "Акация", root: "Акациев" },
    { id: "dark_oak", name: "Темн. дуб", root: "Темно-дубов" },
    { id: "mangrove", name: "Мангр", root: "Мангров" },
    { id: "cherry", name: "Вишня", root: "Вишнев" },
    { id: "crimson", name: "Багров", root: "Багров", isNether: true },
    { id: "warped", name: "Искаж", root: "Искаженн", isNether: true }
];

// --- COPPER ---
const copperTypes = ["", "exposed_", "weathered_", "oxidized_"];
const copperNames = ["Медн", "Потемневш. медн", "Состаренн. медн", "Окисленн. медн"];

// --- STONES ---
const stones = [
    { id: "cobblestone", name: "Булыжник" },
    { id: "mossy_cobblestone", name: "Мшистый булыжник" },
    { id: "stone", name: "Камень" },
    { id: "smooth_stone", name: "Гладкий камень" },
    { id: "stone_bricks", name: "Каменные кирпичи" },
    { id: "mossy_stone_bricks", name: "Мшистые кам. кирпичи" },
    { id: "cracked_stone_bricks", name: "Потреск. кам. кирпичи" },
    { id: "chiseled_stone_bricks", name: "Резные кам. кирпичи" },
    { id: "granite", name: "Гранит" },
    { id: "polished_granite", name: "Полированный гранит" },
    { id: "diorite", name: "Диорит" },
    { id: "polished_diorite", name: "Полированный диорит" },
    { id: "andesite", name: "Андезит" },
    { id: "polished_andesite", name: "Полированный андезит" },
    { id: "deepslate", name: "Глубинный сланец" },
    { id: "cobbled_deepslate", name: "Дробленый сланец" },
    { id: "polished_deepslate", name: "Полированный сланец" },
    { id: "deepslate_bricks", name: "Сланцевые кирпичи" },
    { id: "cracked_deepslate_bricks", name: "Потреск. сланцевые кирпичи" },
    { id: "deepslate_tiles", name: "Сланцевая плитка" },
    { id: "cracked_deepslate_tiles", name: "Потреск. сланцевая плитка" },
    { id: "chiseled_deepslate", name: "Резной сланец" },
    { id: "reinforced_deepslate", name: "Укрепленный сланец" },
    { id: "blackstone", name: "Чернит" },
    { id: "polished_blackstone", name: "Полированный чернит" },
    { id: "polished_blackstone_bricks", name: "Полир. чернит. кирпичи" },
    { id: "cracked_polished_blackstone_bricks", name: "Потреск. полир. чернит. кирпичи" },
    { id: "chiseled_polished_blackstone", name: "Резной полир. чернит" },
    { id: "gilded_blackstone", name: "Золоченый чернит" },
    { id: "end_stone_bricks", name: "Эндерняковые кирпичи" },
    { id: "purpur_block", name: "Пурпурный блок" },
    { id: "purpur_pillar", name: "Пурпурный пилон" },
    { id: "prismarine", name: "Призмарин" },
    { id: "prismarine_bricks", name: "Призмариновые кирпичи" },
    { id: "dark_prismarine", name: "Темный призмарин" },
    { id: "sandstone", name: "Песчаник" },
    { id: "chiseled_sandstone", name: "Резной песчаник" },
    { id: "cut_sandstone", name: "Гладкий песчаник" },
    { id: "red_sandstone", name: "Красный песчаник" },
    { id: "chiseled_red_sandstone", name: "Резной кр. песчаник" },
    { id: "cut_red_sandstone", name: "Гладкий кр. песчаник" },
    { id: "brick_block", name: "Кирпичный блок" },
    { id: "mud_bricks", name: "Грязевые кирпичи" },
    { id: "nether_bricks", name: "Незерские кирпичи" },
    { id: "cracked_nether_bricks", name: "Потреск. незер. кирпичи" },
    { id: "chiseled_nether_bricks", name: "Резные незер. кирпичи" },
    { id: "red_nether_bricks", name: "Красные незер. кирпичи" },
    { id: "quartz_block", name: "Кварцевый блок" },
    { id: "chiseled_quartz_block", name: "Резной кварцевый блок" },
    { id: "quartz_pillar", name: "Кварцевая колонна" },
    { id: "smooth_quartz", name: "Гладкий кварц" }
];

// --- CORALS ---
const corals = ["tube", "brain", "bubble", "fire", "horn"];
const coralNames = ["Трубчатый", "Мозговой", "Пузырчатый", "Огненный", "Роговой"];

// --- POTTERY SHERDS ---
const sherds = ["angler", "archer", "arms_up", "blade", "brewer", "burn", "danger", "explorer", "flow", "friend", "guster", "heart", "heartbreak", "howl", "miner", "mourner", "plenty", "prize", "scrap", "sheaf", "shelter", "skull", "snort"];

// --- SMITHING TEMPLATES ---
const templates = ["netherite_upgrade", "sentry_armor_trim", "dune_armor_trim", "coast_armor_trim", "wild_armor_trim", "ward_armor_trim", "eye_armor_trim", "vex_armor_trim", "tide_armor_trim", "snout_armor_trim", "rib_armor_trim", "spire_armor_trim", "wayfinder_armor_trim", "raiser_armor_trim", "shaper_armor_trim", "host_armor_trim", "silence_armor_trim"];

// --- MUSIC DISCS ---
const discs = ["13", "cat", "blocks", "chirp", "far", "mall", "mellohi", "stal", "strad", "ward", "11", "wait", "otherside", "5", "relic", "precipice", "creator"];

// --- TOOLS & ARMOR ---
const toolMats = ["wooden", "stone", "iron", "golden", "diamond", "netherite"];
const toolTypes = ["sword", "pickaxe", "axe", "shovel", "hoe"];
const armorMats = ["leather", "chainmail", "iron", "golden", "diamond", "netherite"];
const armorTypes = ["helmet", "chestplate", "leggings", "boots"];

// --- BUCKETS ---
const buckets = ["axolotl", "cod", "salmon", "pufferfish", "tropical_fish", "tadpole"];

// --- MISC ITEMS ---
const misc = [
    { id: "coal_ore", name: "Угольная руда" }, { id: "deepslate_coal_ore", name: "Глубинная угольная руда" },
    { id: "iron_ore", name: "Железная руда" }, { id: "deepslate_iron_ore", name: "Глубинная железная руда" },
    { id: "copper_ore", name: "Медная руда" }, { id: "deepslate_copper_ore", name: "Глубинная медная руда" },
    { id: "gold_ore", name: "Золотая руда" }, { id: "deepslate_gold_ore", name: "Глубинная золотая руда" },
    { id: "redstone_ore", name: "Редстоун руда" }, { id: "deepslate_redstone_ore", name: "Глубинная редстоун руда" },
    { id: "emerald_ore", name: "Изумрудная руда" }, { id: "deepslate_emerald_ore", name: "Глубинная изумрудная руда" },
    { id: "lapis_ore", name: "Лазуритовая руда" }, { id: "deepslate_lapis_ore", name: "Глубинная лазуритовая руда" },
    { id: "diamond_ore", name: "Алмазная руда" }, { id: "deepslate_diamond_ore", name: "Глубинная алмазная руда" },
    { id: "nether_gold_ore", name: "Незер-золото" }, { id: "nether_quartz_ore", name: "Кварцевая руда" },
    { id: "ancient_debris", name: "Древние обломки" },
    { id: "raw_iron", name: "Сырое железо", type: "item" }, { id: "raw_iron_block", name: "Блок сырого железа" },
    { id: "raw_copper", name: "Сырая медь", type: "item" }, { id: "raw_copper_block", name: "Блок сырой меди" },
    { id: "raw_gold", name: "Сырое золото", type: "item" }, { id: "raw_gold_block", name: "Блок сырого золота" },

    // Nature
    { id: "dirt", name: "Земля" }, { id: "coarse_dirt", name: "Каменистая земля" }, { id: "rooted_dirt", name: "Корнистая земля" },
    { id: "mud", name: "Грязь" }, { id: "packed_mud", name: "Плотная грязь" }, { id: "clay", name: "Глина" },
    { id: "grass_block", name: "Дерн" }, { id: "podzol", name: "Подзол" }, { id: "mycelium", name: "Мицелий" },
    { id: "sand", name: "Песок" }, { id: "red_sand", name: "Красный песок" }, { id: "gravel", name: "Гравий" },
    { id: "ice", name: "Лёд" }, { id: "blue_ice", name: "Синий лёд" }, { id: "packed_ice", name: "Плотный лёд" },
    { id: "snow_block", name: "Снежный блок" }, { id: "snow", name: "Снежный покров" },
    { id: "obsidian", name: "Обсидиан" }, { id: "crying_obsidian", name: "Плачущий обсидиан" },
    { id: "netherrack", name: "Незерак" }, { id: "soul_sand", name: "Песок душ" }, { id: "soul_soil", name: "Почва душ" },
    { id: "basalt", name: "Базальт" }, { id: "smooth_basalt", name: "Гладкий базальт" }, { id: "polished_basalt", name: "Полированный базальт" },
    { id: "end_stone", name: "Эндерняк" }, { id: "chorus_flower", name: "Цветок хоруса" }, { id: "chorus_plant", name: "Хорус" },
    { id: "cactus", name: "Кактус" }, { id: "bamboo", name: "Бамбук" }, { id: "sugar_cane", name: "Тростник", type: "item" },
    { id: "pumpkin", name: "Тыква" }, { id: "melon", name: "Арбуз" }, { id: "jack_o_lantern", name: "Светильник Джека" }, { id: "carved_pumpkin", name: "Вырезанная тыква" },
    { id: "brown_mushroom", name: "Коричневый гриб" }, { id: "red_mushroom", name: "Красный гриб" },
    { id: "brown_mushroom_block", name: "Блок кор. гриба" }, { id: "red_mushroom_block", name: "Блок кр. гриба" }, { id: "mushroom_stem", name: "Ножка гриба" },
    { id: "shroomlight", name: "Грибосвет" }, { id: "glowstone", name: "Светокамень" }, { id: "sea_lantern", name: "Морской фонарь" },
    { id: "magma_block", name: "Магма" }, { id: "hay_block", name: "Сноп сена" },
    { id: "amethyst_block", name: "Аметистовый блок" }, { id: "budding_amethyst", name: "Цветущий аметист" }, { id: "calcite", name: "Кальцит" }, { id: "tuff", name: "Туф" }, { id: "dripstone_block", name: "Капельник" }, { id: "pointed_dripstone", name: "Сталактит" },
    { id: "moss_block", name: "Блок мха" }, { id: "moss_carpet", name: "Ковер из мха" }, { id: "hanging_roots", name: "Свисающие корни" },
    { id: "spore_blossom", name: "Спороцвет" }, { id: "azalea", name: "Азалия" }, { id: "flowering_azalea", name: "Цветущая азалия" }, { id: "azalea_leaves", name: "Листья азалии" }, { id: "flowering_azalea_leaves", name: "Цветущие листья азалии" },
    { id: "big_dripleaf", name: "Большой бросянка" }, { id: "small_dripleaf", name: "Малый бросянка" }, { id: "glow_lichen", name: "Светящийся лишайник" },
    { id: "sculk", name: "Скалк" }, { id: "sculk_vein", name: "Скалк-жила" }, { id: "sculk_catalyst", name: "Скалк-катализатор" }, { id: "sculk_shrieker", name: "Скалк-крикун" },
    { id: "ochre_froglight", name: "Охристый жабосвет" }, { id: "verdant_froglight", name: "Зеленый жабосвет" }, { id: "pearlescent_froglight", name: "Перламутровый жабосвет" },
    { id: "mangrove_roots", name: "Мангровые корни" }, { id: "muddy_mangrove_roots", name: "Грязные корни" },
    { id: "vine", name: "Лианы" }, { id: "weeping_vines", name: "Плакучие лианы" }, { id: "twisting_vines", name: "Вьющиеся лианы" },
    { id: "lily_pad", name: "Кувшинка" }, { id: "sea_pickle", name: "Морской огурец" }, { id: "kelp", name: "Ламинария", type: "item" }, { id: "seagrass", name: "Морская трава" },

    // Functional & Decor
    { id: "crafting_table", name: "Верстак" }, { id: "furnace", name: "Печь" }, { id: "blast_furnace", name: "Плавильная печь" }, { id: "smoker", name: "Коптильня" },
    { id: "cartography_table", name: "Стол картографа" }, { id: "fletching_table", name: "Стол лучника" }, { id: "grindstone", name: "Точило" },
    { id: "smithing_table", name: "Стол кузнеца" }, { id: "stonecutter", name: "Камнерез" }, { id: "loom", name: "Ткацкий станок" },
    { id: "barrel", name: "Бочка" }, { id: "chest", name: "Сундук" }, { id: "ender_chest", name: "Эндер-сундук" },
    { id: "shulker_box", name: "Шалкеровый ящик" }, { id: "beacon", name: "Маяк" }, { id: "conduit", name: "Морской источник" },
    { id: "respawn_anchor", name: "Якорь возрождения" }, { id: "lodestone", name: "Магнетит" },
    { id: "bee_nest", name: "Пчелиное гнездо" }, { id: "beehive", name: "Улей" }, { id: "honey_block", name: "Блок мёда" }, { id: "honeycomb_block", name: "Блок сот" },
    { id: "scaffolding", name: "Подмостки" }, { id: "ladder", name: "Лестница" }, { id: "chain", name: "Цепь", type: "item" }, { id: "iron_bars", name: "Железные прутья" },
    { id: "anvil", name: "Наковальня" }, { id: "chipped_anvil", name: "Поврежд. наковальня" }, { id: "damaged_anvil", name: "Разбитая наковальня" },
    { id: "enchanting_table", name: "Чародейский стол" }, { id: "bookshelf", name: "Книжная полка" }, { id: "chiseled_bookshelf", name: "Резная кн. полка" },
    { id: "brewing_stand", name: "Варочная стойка", type: "item" }, { id: "cauldron", name: "Котел", type: "item" }, { id: "bell", name: "Колокол" }, { id: "composter", name: "Компостер" },
    { id: "lantern", name: "Фонарь" }, { id: "soul_lantern", name: "Фонарь душ" }, { id: "campfire", name: "Костер" }, { id: "soul_campfire", name: "Костер душ" },
    { id: "end_rod", name: "Стержень Энда" }, { id: "flower_pot", name: "Цветочный горшок" }, { id: "armor_stand", name: "Стойка для брони", type: "item" },
    { id: "painting", name: "Картина", type: "item" }, { id: "item_frame", name: "Рамка", type: "item" }, { id: "glow_item_frame", name: "Светящаяся рамка", type: "item" },
    { id: "skeleton_skull", name: "Череп скелета" }, { id: "wither_skeleton_skull", name: "Череп визер-скелета" }, { id: "zombie_head", name: "Голова зомби" }, { id: "creeper_head", name: "Голова крипера" }, { id: "dragon_head", name: "Голова дракона" }, { id: "piglin_head", name: "Голова пиглина" },

    // Food
    { id: "apple", name: "Яблоко", type: "item", fast: true },
    { id: "mushroom_stew", name: "Тушеные грибы", type: "item", fast: true },
    { id: "bread", name: "Хлеб", type: "item", fast: true },
    { id: "porkchop", name: "Свинина", type: "item", fast: true },
    { id: "cooked_porkchop", name: "Жареная свинина", type: "item", fast: true },
    { id: "golden_carrot", name: "Золотая морковь", type: "item", fast: false },
    { id: "cake", name: "Торт", type: "block", fast: false },
    { id: "cookie", name: "Печенье", type: "item", fast: true },
    { id: "melon_slice", name: "Ломтик арбуза", type: "item", fast: true },
    { id: "dried_kelp", name: "Сушеная ламинария", type: "item", fast: true },
    { id: "beef", name: "Говядина", type: "item", fast: true },
    { id: "cooked_beef", name: "Стейк", type: "item", fast: true },
    { id: "chicken", name: "Курятина", type: "item", fast: true },
    { id: "cooked_chicken", name: "Жареная курятина", type: "item", fast: true },
    { id: "rotten_flesh", name: "Гнилая плоть", type: "item", fast: true },
    { id: "spider_eye", name: "Паучий глаз", type: "item", fast: true },
    { id: "carrot", name: "Морковь", type: "item", fast: true },
    { id: "potato", name: "Картофель", type: "item", fast: true },
    { id: "baked_potato", name: "Печеный картофель", type: "item", fast: true },
    { id: "poisonous_potato", name: "Ядовитый картофель", type: "item", fast: true },
    { id: "pumpkin_pie", name: "Тыквенный пирог", type: "item", fast: false },
    { id: "rabbit", name: "Крольчатина", type: "item", fast: true },
    { id: "cooked_rabbit", name: "Жареная крольчатина", type: "item", fast: true },
    { id: "rabbit_stew", name: "Рагу из кролика", type: "item", fast: false },
    { id: "mutton", name: "Баранина", type: "item", fast: true },
    { id: "cooked_mutton", name: "Жареная баранина", type: "item", fast: true },
    { id: "beetroot", name: "Свекла", type: "item", fast: true },
    { id: "beetroot_soup", name: "Свекольный суп", type: "item", fast: true },
    { id: "sweet_berries", name: "Сладкие ягоды", type: "item", fast: true },
    { id: "glow_berries", name: "Светящиеся ягоды", type: "item", fast: true },
    { id: "honey_bottle", name: "Бутылочка меда", type: "item", fast: false },
    { id: "cod", name: "Треска", type: "item", fast: true },
    { id: "cooked_cod", name: "Жареная треска", type: "item", fast: true },
    { id: "salmon", name: "Лосось", type: "item", fast: true },
    { id: "cooked_salmon", name: "Жареный лосось", type: "item", fast: true },
    { id: "tropical_fish", name: "Тропическая рыба", type: "item", fast: true },
    { id: "pufferfish", name: "Иглобрюх", type: "item", fast: true },

    // Items
    { id: "totem_of_undying", name: "Тотем бессмертия", type: "item" },
    { id: "elytra", name: "Элитры", type: "item" },
    { id: "trident", name: "Трезубец", type: "item" },
    { id: "shield", name: "Щит", type: "item" },
    { id: "crossbow", name: "Арбалет", type: "item" },
    { id: "bow", name: "Лук", type: "item" },
    { id: "arrow", name: "Стрела", type: "item" },
    { id: "spectral_arrow", name: "Спектральная стрела", type: "item" },
    { id: "golden_apple", name: "Золотое яблоко", type: "item" },
    { id: "enchanted_golden_apple", name: "Зачарованное яблоко", type: "item" },
    { id: "ender_pearl", name: "Жемчуг Эндера", type: "item" },
    { id: "ender_eye", name: "Око Эндера", type: "item" },
    { id: "firework_rocket", name: "Фейерверк", type: "item" },
    { id: "fire_charge", name: "Огненный шар", type: "item" },
    { id: "bucket", name: "Ведро", type: "item" },
    { id: "water_bucket", name: "Ведро воды", type: "item" },
    { id: "lava_bucket", name: "Ведро лавы", type: "item" },
    { id: "milk_bucket", name: "Ведро молока", type: "item" },
    { id: "powder_snow_bucket", name: "Ведро рыхлого снега", type: "item" },
    { id: "fishing_rod", name: "Удочка", type: "item" },
    { id: "flint_and_steel", name: "Огниво", type: "item" },
    { id: "shears", name: "Ножницы", type: "item" },
    { id: "spyglass", name: "Подзорная труба", type: "item" },
    { id: "map", name: "Карта", type: "item" },
    { id: "compass", name: "Компас", type: "item" },
    { id: "recovery_compass", name: "Возвратный компас", type: "item" },
    { id: "clock", name: "Часы", type: "item" },
    { id: "name_tag", name: "Бирка", type: "item" },
    { id: "lead", name: "Поводок", type: "item" },
    { id: "saddle", name: "Седло", type: "item" },
    { id: "flint", name: "Кремень", type: "item" },
    { id: "coal", name: "Уголь", type: "item" },
    { id: "charcoal", name: "Древесный уголь", type: "item" },
    { id: "diamond", name: "Алмаз", type: "item" },
    { id: "iron_ingot", name: "Железный слиток", type: "item" },
    { id: "gold_ingot", name: "Золотой слиток", type: "item" },
    { id: "copper_ingot", name: "Медный слиток", type: "item" },
    { id: "netherite_ingot", name: "Незеритовый слиток", type: "item" },
    { id: "stick", name: "Палка", type: "item" },
    { id: "bowl", name: "Миска", type: "item" },
    { id: "string", name: "Нить", type: "item" },
    { id: "feather", name: "Перо", type: "item" },
    { id: "gunpowder", name: "Порох", type: "item" },
    { id: "wheat", name: "Пшеница", type: "item" },
    { id: "wheat_seeds", name: "Семена пшеницы", type: "item" },
    { id: "leather", name: "Кожа", type: "item" },
    { id: "clay_ball", name: "Глина (предмет)", type: "item" },
    { id: "paper", name: "Бумага", type: "item" },
    { id: "book", name: "Книга", type: "item" },
    { id: "slime_ball", name: "Сгусток слизи", type: "item" },
    { id: "egg", name: "Яйцо", type: "item" },
    { id: "glowstone_dust", name: "Светокаменная пыль", type: "item" },
    { id: "ink_sac", name: "Чернильный мешок", type: "item" },
    { id: "lapis_lazuli", name: "Лазурит", type: "item" },
    { id: "bone_meal", name: "Костная мука", type: "item" },
    { id: "bone", name: "Кость", type: "item" },
    { id: "sugar", name: "Сахар", type: "item" },
    { id: "nether_star", name: "Звезда Незера", type: "item" },
    { id: "brick", name: "Кирпич (предмет)", type: "item" },
    { id: "nether_brick", name: "Незерский кирпич (предмет)", type: "item" },
    { id: "quartz", name: "Кварц", type: "item" },
    { id: "prismarine_shard", name: "Призмариновый осколок", type: "item" },
    { id: "prismarine_crystals", name: "Призмариновый кристалл", type: "item" },
    { id: "rabbit_hide", name: "Кроличья шкурка", type: "item" },
    { id: "rabbit_foot", name: "Кроличья лапка", type: "item" },
    { id: "phantom_membrane", name: "Мембрана фантома", type: "item" },
    { id: "nautilus_shell", name: "Раковина наутилуса", type: "item" },
    { id: "heart_of_the_sea", name: "Сердце моря", type: "item" },
    { id: "honeycomb", name: "Медовые соты", type: "item" },
    { id: "amethyst_shard", name: "Осколок аметиста", type: "item" },
    { id: "echo_shard", name: "Осколок эха", type: "item" },
    { id: "disc_fragment_5", name: "Фрагмент пластинки 5", type: "item" },
    { id: "slime_block", name: "Блок слизи" }, { id: "tnt", name: "Динамит" },

    // 1.21
    { id: "crafter", name: "Автокрафтер", type: "block" },
    { id: "copper_bulb", name: "Медная лампа", type: "block" },
    { id: "trial_spawner", name: "Рассадник испытаний", type: "block" },
    { id: "vault", name: "Хранилище", type: "block" },
    { id: "heavy_core", name: "Тяжелое ядро", type: "block" },
    { id: "breeze_rod", name: "Стержень бриза", type: "item" },
    { id: "mace", name: "Булава", type: "item" },
    { id: "wind_charge", name: "Заряд ветра", type: "item" },
    { id: "ominous_bottle", name: "Зловещая бутылочка", type: "item" },
    { id: "trial_key", name: "Ключ испытаний", type: "item" },
    { id: "sniffer_egg", name: "Яйцо нюхача", type: "block" },
    { id: "torchflower", name: "Факельник", type: "block" },
    { id: "pitcher_plant", name: "Кувшиночник", type: "block" },
    { id: "brush", name: "Кисть", type: "item" }
];
