name: SpeedrunPlugin
version: 1.8.0
main: com.speedrun.SpeedrunPlugin
api-version: '1.21'
description: Item Speedrun Competition Plugin
author: Randomizer

commands:
  speedrun:
    description: Speedrun competition commands
    usage: /speedrun <start|stop|pause|resume|status> [args...]
    permission: speedrun.use

permissions:
  speedrun.use:
    description: Allows using speedrun commands
    default: op
